//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiterQR.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int ID { get; set; }
        public int OwnerID { get; set; }
        public int PostalCode { get; set; }
        public string City { get; set; }
        public string StreetName { get; set; }
        public int HouseNo { get; set; }
        public int TableAmount { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
