//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiterQR.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int RestaurantID { get; set; }
        public int OwnerID { get; set; }
        public int RestaurantPostalCode { get; set; }
        public string Restaurant_City { get; set; }
        public string Restaurant_StreetName { get; set; }
        public string Restaurant_HouseNo { get; set; }
    }
}
