//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiterQR.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurants
    {
        public int Restaurant_Id { get; set; }
        public string Owner_LastName { get; set; }
        public string Owner_FirstName { get; set; }
        public string Restaurant_City { get; set; }
        public int Restaurant_PostalCode { get; set; }
        public string Restaurant_StreetName { get; set; }
    }
}
