//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiterQR.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ShoppingCartID { get; set; }
        public int UserID { get; set; }
        public int ProductIDs { get; set; }
        public int ProductCount { get; set; }
        public int RestaurantID { get; set; }
        public int RestaurantIDTable { get; set; }
        public int OrderStatus { get; set; }
    }
}
